import { definePageCopy } from '../define';
import { siteConfig } from '@/lib/site';

/**
 * Site-wide (header, footer, contact) — editable text. Fields are added here with their current wording as the default; the
 * page component reads them from the copy it is given instead of hard-coding the string.
 *
 * Env-driven values stay env-driven by default: `contact.phone` falls back from NEXT_PUBLIC_PHONE to the
 * published helpline exactly as the footer and the mobile bar did before. The WhatsApp number
 * (NEXT_PUBLIC_WHATSAPP_NUMBER) is not a field — it is read from `siteConfig` in code.
 */
export const siteCopy = definePageCopy({
  id: 'site',
  label: 'Site-wide (header, footer, contact)',
  path: undefined,
  group: 'Site',
  description: 'Navigation, footer, contact details, social links, calls to action and error pages.',
  defaults: {
    // Default metadata for every page that does not set its own.
    'seo.title': `${siteConfig.name} — ${siteConfig.tagline}`,
    'seo.titleTemplate': `%s | ${siteConfig.name}`,
    'seo.description': siteConfig.description,

    'a11y.skipToContent': 'Skip to content',

    // Header
    'header.logo.alt': siteConfig.name,
    'header.logo.ariaLabel': `${siteConfig.name} home`,
    'header.nav.ariaLabel': 'Primary',
    'header.nav.0.label': 'About Us',
    'header.nav.0.href': '/about-us',
    'header.nav.1.label': 'Courses',
    'header.nav.1.href': '/courses',
    'header.nav.2.label': 'Centres',
    'header.nav.2.href': '/centres',
    'header.nav.3.label': 'Placements',
    'header.nav.3.href': '/placements',
    'header.nav.4.label': 'Franchise',
    'header.nav.4.href': '/franchise',
    'header.nav.5.label': 'Investors',
    'header.nav.5.href': '/investors',
    'header.nav.6.label': 'Blog',
    'header.nav.6.href': '/blog',
    'header.cta.label': 'Enquire Now',
    'header.ai.label': 'Jetking AI',
    'header.ai.ariaLabel': 'Open Jetking AI assistant',
    'header.theme.toLight': 'Switch to light mode',
    'header.theme.toDark': 'Switch to dark mode',
    'header.account.login': 'Log in',
    'header.account.loginOrSignup': 'Log in / Sign up',
    'header.account.logout': 'Log out',
    'header.account.myAccount': 'My account · {name}',
    'header.account.ariaLabel': 'Your account ({name})',
    'header.menu.openLabel': 'Open menu',
    'header.menu.closeLabel': 'Close menu',
    'header.drawer.title': 'Menu',
    'header.drawer.ariaLabel': 'Site menu',
    'header.drawer.navAriaLabel': 'Main',
    'header.coursesMenu.groupsAriaLabel': 'Course groups',
    'header.coursesMenu.levelHeading': 'Level',
    'header.coursesMenu.technologyHeading': 'Technology',
    'header.coursesMenu.allCourses': 'All courses',
    'header.coursesMenu.viewAllLevel': 'View all {level} courses',
    'header.coursesMenu.viewAllTechnology': 'View all {technology} courses',
    'header.coursesMenu.listAriaLabel': '{group} courses',

    // Contact details
    'contact.address': '5th Floor, Amore Building, Junction of 2nd & 4th Road, Khar, Mumbai – 400052, India',
    'contact.email': 'info@jetking.com',
    'contact.phone': siteConfig.phone || siteConfig.helpline,

    // Mobile contact bar
    'mobileBar.call.label': 'Call us',
    'mobileBar.whatsapp.ariaLabel': 'Chat on WhatsApp',
    'mobileBar.enquire.label': 'Enquire now',

    // "Not sure which course?" nudge
    'askAi.prompt': 'Not sure which course?',
    'askAi.link': 'Ask Jetking AI',
    'askAi.href': '/chatbot',

    // Footer
    'footer.logo.alt': siteConfig.name,
    'footer.description': siteConfig.description,
    'footer.social.heading': 'Follow us',
    'footer.social.ariaLabel': 'Jetking on social media',
    'footer.social.newTabHint': ' (opens in a new tab)',
    'footer.social.0.label': 'Jetking on Facebook',
    'footer.social.0.href': 'https://www.facebook.com/JetkingOfficial/',
    'footer.social.1.label': 'Jetking on Instagram',
    'footer.social.1.href': 'https://www.instagram.com/jetkingofficial/',
    'footer.social.2.label': 'Jetking on YouTube',
    'footer.social.2.href': 'https://www.youtube.com/c/JetkingOfficial',
    'footer.social.3.label': 'Jetking on LinkedIn',
    'footer.social.3.href': 'https://in.linkedin.com/company/jetking',
    'footer.social.4.label': 'Jetking on Twitter (X)',
    'footer.social.4.href': 'https://twitter.com/JetkingLtd',
    'footer.courses.heading': 'Courses',
    'footer.courses.viewAll': 'View all courses',
    'footer.centres.heading': 'Centres',
    'footer.centres.cityLink': 'IT courses in {city}',
    'footer.centres.viewAll': 'View all centres',
    'footer.company.heading': 'Company',
    'footer.company.0.label': 'About Us',
    'footer.company.0.href': '/about-us',
    'footer.company.1.label': 'Placements',
    'footer.company.1.href': '/placements',
    'footer.company.2.label': 'Franchise',
    'footer.company.2.href': '/franchise',
    'footer.company.3.label': 'Investors',
    'footer.company.3.href': '/investors',
    'footer.company.4.label': 'Blog',
    'footer.company.4.href': '/blog',
    'footer.company.5.label': 'FAQ',
    'footer.company.5.href': '/faq',
    'footer.company.6.label': 'Enquire',
    'footer.company.6.href': '/enquiry',
    'footer.company.7.label': 'Sitemap',
    'footer.company.7.href': '/sitemap',
    'footer.copyright': `© {year} ${siteConfig.legalName}. All rights reserved.`,
    'footer.legal.ariaLabel': 'Legal',
    'footer.legal.0.label': 'Privacy Policy',
    'footer.legal.0.href': '/privacy-policy',
    'footer.legal.1.label': 'Terms & Conditions',
    'footer.legal.1.href': '/terms-conditions',
    'footer.legal.2.label': 'Enrollment Terms',
    'footer.legal.2.href': '/enrollment-terms-and-conditions',
    'footer.tagline': 'India’s No.1 Technology Training Institute',

    // Enquiry pop-up (the "Enquire now" sheet) and the short form it shares with the centres/courses banner card
    'enquiry.modal.title': 'Enquire now',
    'enquiry.modal.intro': 'Tell us where you are and a Jetking counsellor from your nearest centre will call you.',
    'enquiry.modal.closeLabel': 'Close',
    'enquiry.modal.closeButton': 'Close',
    'enquiry.heroCard.title': 'Quick enquiry',
    'enquiry.form.name.label': 'Your name',
    'enquiry.form.mobile.label': 'Mobile number',
    'enquiry.form.mobile.placeholder': '+91 98765 43210',
    'enquiry.form.state.label': 'State',
    'enquiry.form.state.placeholder': 'Select state',
    'enquiry.form.city.label': 'City',
    'enquiry.form.city.placeholder': 'Select city',
    'enquiry.form.city.disabledPlaceholder': 'State first',
    'enquiry.form.centre.label': 'Centre',
    'enquiry.form.centre.placeholder': 'Select centre',
    'enquiry.form.centre.disabledPlaceholder': 'City first',
    'enquiry.form.qualification.label': 'Highest qualification',
    'enquiry.form.qualification.placeholder': 'Qualification',
    'enquiry.form.submit': 'Submit',
    'enquiry.form.submitting': 'Submitting…',
    'enquiry.form.privacyNote': 'We use your details only to respond to this enquiry.',
    'enquiry.success.title': 'Thank you!',
    'enquiry.success.body': 'A counsellor from your chosen centre will get in touch, usually within one working day.',
    'enquiry.error.generic': 'Something went wrong. Please try again.',
    'enquiry.error.network': 'We could not send that. Please check your connection and try again.',

    // Exit-intent pop-up
    'exitIntent.title': 'Before you go —',
    'exitIntent.body': 'Leave your number and a Jetking counsellor will help you pick the right course. No spam, no pressure.',
    'exitIntent.closeLabel': 'Close',
    'exitIntent.name.label': 'Name',
    'exitIntent.name.placeholder': 'Your full name',
    'exitIntent.mobile.label': 'Mobile Number',
    'exitIntent.mobile.placeholder': '+91 98765 43210',
    'exitIntent.email.label': 'Email Address',
    'exitIntent.email.placeholder': 'you@example.com',
    'exitIntent.submit': 'Talk to a counsellor',
    'exitIntent.submitting': 'Submitting…',
    'exitIntent.success.title': 'Thank you!',
    'exitIntent.success.body': 'We’ll reach out only if you want us to — no spam, no pressure.',

    // 404 page
    'errors.notFound.eyebrow': 'Error 404',
    'errors.notFound.title': 'We couldn’t find that page',
    'errors.notFound.body':
      'The link may be old, or the page may have moved during our site migration. Try one of the places below, or tell us what you were looking for and a counsellor will point you to it.',
    'errors.notFound.primaryCta.label': 'Back to home',
    'errors.notFound.primaryCta.href': '/',
    'errors.notFound.secondaryCta.label': 'Browse courses',
    'errors.notFound.secondaryCta.href': '/courses',
    'errors.notFound.destinations.heading': 'Where would you like to go?',
    'errors.notFound.destinations.0.title': 'Courses',
    'errors.notFound.destinations.0.meta': 'Degrees, diplomas and short courses',
    'errors.notFound.destinations.0.href': '/courses',
    'errors.notFound.destinations.1.title': 'Centres',
    'errors.notFound.destinations.1.meta': '39 centres across 28 cities',
    'errors.notFound.destinations.1.href': '/centres',
    'errors.notFound.destinations.2.title': 'Placements',
    'errors.notFound.destinations.2.meta': 'How placement support works',
    'errors.notFound.destinations.2.href': '/placements',
    'errors.notFound.destinations.3.title': 'Guidance',
    'errors.notFound.destinations.3.meta': 'Choosing a course and a career',
    'errors.notFound.destinations.3.href': '/blog',
    'errors.notFound.destinations.4.title': 'Franchise',
    'errors.notFound.destinations.4.meta': 'The operating model',
    'errors.notFound.destinations.4.href': '/franchise',
    'errors.notFound.destinations.5.title': 'Talk to a counsellor',
    'errors.notFound.destinations.5.meta': 'Get a call back, free',
    'errors.notFound.destinations.5.href': '/enquiry',

    // Error page (a page failed while rendering)
    'errors.route.eyebrow': 'Something went wrong',
    'errors.route.title': 'We hit a problem loading this page',
    'errors.route.body': 'It is on our side, and we have been told. Try again, or head back to the home page.',
    'errors.route.retryLabel': 'Try again',
    'errors.route.homeLabel': 'Back to home',
    'errors.route.homeHref': '/',
    'errors.route.reference': 'Reference: {digest}',
  },
});

export type SiteCopy = typeof siteCopy.defaults;
